scikit-learn-contrib/lightning

lightning/impl/randomkit/setup.py

I took this info from the numpy conterpart, and seems to work.
Tested on Windows 8.

FIX: compile on windows require to link against Advapi32.

---

Makefile

`make all` and `make test` were not working because of this. Is this the intended fix?

Remove missing make targets

---

MANIFEST.in
lightning/impl/setup.py

I ran 
```
python setup.py sdist
[go to basic venv]
pip install dist/sklearn-contrib-lightning-0.3.dev0.tar.gz
[go to my package]
[regenerate cython files]
[build]
[test]
```
and it worked like a charm.
Side by side diff of the last release vs sdist on this branch.
```
sklearn-contrib-lightning-0.3.dev0/ | sklearn-contrib-lightning-0.2.0/
├── bin                             ├── bin
│   ├── lightning_predict           │   ├── lightning_predict
│   └── lightning_train             │   └── lightning_train
├── lightning                       ├── lightning
│   ├── classification.py           │   ├── classification.py
│   ├── datasets.py                 │   ├── datasets.py
│   ├── impl                        │   ├── impl
│   │   ├── adagrad_fast.cpp        │   │   ├── adagrad_fast.cpp
│   │   …
```

Add MANIFEST.in to include pxd files in releases

---

lightning/impl/sag.py
lightning/impl/sag_fast.cpp
lightning/impl/sag_fast.pyx
lightning/impl/tests/test_sag.py

This is important when one has the data in a custom Dataset format
and doesn't want to convert to numpy arrays/sparse matrices, e.g.
when data does not fit in memory.
The biggest change is to code get_auto_step_size to accept a Dataset object, which was previously coded for numpy/sparse matrices.

ENH: allow SAG* objects to take a RowDataset as argument.

---

lightning/impl/base.py
lightning/impl/tests/test_adagrad.py
lightning/impl/tests/test_dual_cd.py
lightning/impl/tests/test_primal_cd.py
lightning/impl/tests/test_sag.py
lightning/impl/tests/test_sdca.py
lightning/impl/tests/test_sgd.py
lightning/impl/tests/test_svrg.py
lightning/impl/tests/utils.py

In scikit-learn when predit_proba method is not available, AttributeError is raised instead of NotImplementedError. In this PR:
- classifiers are changed to follow the same convention;
- removed predict_log_proba mentions because lightning doesn't provide this method;
- added more tests for predict_proba results.

raise AttributeError if predict_proba is not available

---

lightning/impl/fista.py
lightning/impl/tests/test_fista.py

According to the original FISTA paper [Beck09].
[Beck09] Beck, Amir, and Marc Teboulle. "A fast iterative shrinkage-thresholding algorithm for linear inverse problems." SIAM journal on imaging sciences 2.1 (2009): 183-202.

Stepsize update rule changed in fista.py

---

lightning/impl/sgd_fast.pyx

Class variables are already defined in the .pxd. I believe this should get rid of intermittent Travis failures.
For more details about the cythonization error, see:
https://github.com/scikit-learn-contrib/lightning/pull/105#issuecomment-276957093

[MRG] Fix cythonization error in sgd_fast.pyx

---

lightning/impl/prox_fast.pxd
lightning/impl/prox_fast.pyx
lightning/impl/tests/test_prox.py

Use fused types to support float32 in fused lasso (pun intended)

[MRG] support float3d in prox_tv1d

---

.travis.yml
appveyor.yml
benchmarks/bench_amazon7.py
doc/sphinxext/gen_rst.py
lightning/impl/adagrad.py
lightning/impl/datasets/samples_generator.py
lightning/impl/dual_cd.py
lightning/impl/fista.py
lightning/impl/primal_cd.py
lightning/impl/primal_newton.py
lightning/impl/randomkit/tests/test_random.py
lightning/impl/sag.py
lightning/impl/sdca.py
lightning/impl/sgd.py
lightning/impl/svrg.py
lightning/impl/tests/test_dataset.py
lightning/impl/tests/test_dual_cd.py
lightning/impl/tests/test_penalty.py
lightning/impl/tests/test_primal_cd.py
setup.py

This PR will allow using `lightning` with the latest version (`0.23.0`) of `scikit-learn`.
Right now if you try to upgrade `scikit-learn`, `lightning` fails with the error about that it cannot import neither `joblib` nor `six` because they are no longer exist in `sklearn.externals`:
```
from lightning.classification import KernelSVC
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/lightning/classification.py:1: in <module>
from .impl.adagrad import AdaGradClassifier
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/lightning/impl/adagrad.py:8: in <module>
from sklearn.externals.six.moves import xrange
```
`six` was dropped along with Python 2 support.
https://scikit-learn.org/stable/whats_new/v0.21.html#sklearn-externals
`joblib` is now a dependency: …

[HOTFIX] fix compatibility with new scikit-learn version

---

MANIFEST.in

For packaging with `conda-forge` it would be useful to include the `Makefile` in the sdist.
https://github.com/conda-forge/sklearn-contrib-lightning-feedstock/pull/12/files#r546366624

Add Makefile to MANIFEST.in

---

lightning/impl/primal_cd.py

This is to address issue #150 
(I'm not sure which branch to merge to)

Removing `CDRegressor` docstrings references to nonnegative penalties

---

lightning/impl/datasets/tests/test_samples_generator.py
lightning/impl/randomkit/tests/test_random.py
lightning/impl/tests/test_adagrad.py
lightning/impl/tests/test_dataset.py
lightning/impl/tests/test_dual_cd.py
lightning/impl/tests/test_fista.py
lightning/impl/tests/test_penalty.py
lightning/impl/tests/test_prank.py
lightning/impl/tests/test_primal_cd.py
lightning/impl/tests/test_primal_newton.py
lightning/impl/tests/test_prox.py
lightning/impl/tests/test_sag.py
lightning/impl/tests/test_sdca.py
lightning/impl/tests/test_sgd.py
lightning/impl/tests/test_svrg.py
lightning/impl/tests/utils.py

Fixed #156.
Use normal `assert`s and ones from `numpy.testing` module where normal ones cannot be used (approx, arrays, raises).

fix compatibility with scikit-learn by dropping dependency from sklearn.testing

---

.travis.yml
appveyor.yml

https://devguide.python.org/#status-of-python-branches
All other versions have reached their EOL.

Run tests with actual Python versions

---

doc/sphinxext/gen_rst.py
examples/plot_1d_total_variation.py
lightning/impl/datasets/samples_generator.py
lightning/impl/tests/test_sag.py

Fix
```
/home/travis/build/scikit-learn-contrib/lightning/lightning/impl/datasets/samples_generator.py:236: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
y = np.zeros(n_samples, dtype=np.int)
```
and
```
impl/tests/test_sag.py::test_sag_sample_weights
/home/travis/build/scikit-learn-contrib/lightning/lightning/impl/tests/test_sag.py:444: …
```

Fix numpy deprecation warnings

---

lightning/impl/adagrad.py
lightning/impl/datasets/samples_generator.py
lightning/impl/dual_cd.py
lightning/impl/sdca.py
lightning/impl/svrg.py
lightning/impl/tests/test_fista.py
lightning/impl/tests/test_primal_cd.py
lightning/impl/tests/test_sag.py
lightning/impl/tests/test_svrg.py

Fix
```
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_class=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
"will result in an error", FutureWarning)
```

Fix compatibility with upcoming scikit-learn release and remove unused imports

---

.travis.yml
README.rst
appveyor.yml
build_tools/windows/windows_testing_downloader.ps1
lightning/impl/tests/test_prox.py
lightning/impl/tests/test_sag.py

https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-as-part-of-application-code

migrate from nose to pytest

---

lightning/impl/adagrad.py
lightning/impl/dual_cd.py
lightning/impl/fista.py
lightning/impl/prank.py
lightning/impl/primal_cd.py
lightning/impl/primal_newton.py
lightning/impl/sag.py
lightning/impl/sdca.py
lightning/impl/sgd.py
lightning/impl/svrg.py

There are a lot of LaTeX formulas in doctrings for `__init__()` methods which cause warnings like the following one:
```
lightning/impl/adagrad.py:59
/home/travis/build/scikit-learn-contrib/lightning/lightning/impl/adagrad.py:59: DeprecationWarning: invalid escape sequence \s
"""
```

use raw strings in docstrings for __init__

---

lightning/impl/dataset_fast.pxd
lightning/impl/prox_fast.pxd
lightning/impl/prox_fast.pyx
lightning/impl/randomkit/random_fast.pxd
lightning/impl/randomkit/random_fast.pyx
lightning/impl/sag_fast.pxd
lightning/impl/sgd_fast.pxd

Fix
```
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/travis/build/scikit-learn-contrib/lightning/lightning/impl/dataset_fast.pxd
```
Linking #134.

add Cython directives to pxd files

---

.github/workflows/gh_pages.yml
doc/conf.py
doc/requirements.txt
requirements.txt
requirements_build.txt
requirements_test.txt
setup.py

Refer to https://github.com/scikit-learn-contrib/lightning/pull/172#issuecomment-837124387.
Closed #172.
You can find a result of these enhancements in my forked repo:
- https://github.com/StrikerRUS/lightning/runs/2579745437?check_suite_focus=true
- https://github.com/StrikerRUS/lightning/commits/gh-pages
- https://github.com/StrikerRUS/lightning/commit/0a35a8d2e5cf1df683f4140695d65b3958728394

deploy docs automatically with every commit in `master`

---

doc/conf.py
examples/document_classification_news20.py
examples/plot_sparse_non_linear.py
examples/trace.py

By executing all examples regardless they have plots or not, we make sure they are runnable and up-to-date.
> By default, Sphinx-Gallery will **parse and add** all files with a `.py` extension to the gallery, but only **execute** files beginning with `plot_`.
https://sphinx-gallery.github.io/stable/configuration.html#parsing-and-executing-examples-via-matching-patterns

execute all examples in gallery and prettify printed info

---

.github/workflows/main.yml

Wheels for all platforms and source archive will be automatically uploaded to Releases tab with each tagged commit.
For example please refer to https://github.com/StrikerRUS/lightning/releases/tag/untagged-a19e7c8d925f0295f2b6.
Unfortunately, neither `manylinux2010` nor `manylinux1` containers cannot be used due to the following restriction of Node.js: https://github.com/actions/runner/issues/337. But I think `manylinux2014` is better than nothing. Moreover, CentOS 6 and CentOS 5 on which those containers are based have already reached their EOL.
https://github.com/pypa/manylinux

Build artifacts at GitHub Actions

---

.github/workflows/main.yml
README.rst
setup.py

Python 3.6 is reaching its End of Life tomorrow and no need to support it anymore.
https://devguide.python.org/#branchstatus

Drop Python 3.6 support

---

.github/workflows/gh_pages.yml

Pin Python version to `3.9` in docs generating workflow (default is `3.10`) to avoid installing `scipy` from sources and the following error:
```
Processing dependencies for sklearn-contrib-lightning==0.6.2.dev0
Searching for scipy
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/29/d2/151a54944b333e465f98804dced31dab1284f3c37b752b9cefa710b64681/scipy-1.8.0rc2.tar.gz#sha256=d73b13eb0452c178f946b4db60b27e400225df02e926609652ed67798054e77d
Best match: scipy 1.8.0rc2
Processing scipy-1.8.0rc2.tar.gz
Writing /tmp/easy_install-we9rlw9q/scipy-1.8.0rc2/setup.cfg
Running scipy-1.8.0rc2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-we9rlw9q/scipy-1.8.0rc2/egg-dist-tmp-r9r7tpz2
/tmp/easy_install-we9rlw9q/scipy-1.8.0rc2/setup.py:481: UserWarning: …
```

Fix documentation building

---

lightning/impl/tests/test_primal_cd.py

Fix flaky test originally reported in https://github.com/scikit-learn-contrib/lightning/pull/187#issuecomment-999236047.
I'm not limiting `if` branch to 32-bit Windows because during preparing this PR I was observing the same test failures on 64-bit Windows as well: https://github.com/scikit-learn-contrib/lightning/runs/4637338353?check_suite_focus=true.

Relax assert for number of non-zero elements in test

---

.github/workflows/main.yml
lightning/impl/tests/conftest.py
lightning/impl/tests/test_adagrad.py
lightning/impl/tests/test_dataset.py
lightning/impl/tests/test_dual_cd.py
lightning/impl/tests/test_fista.py
lightning/impl/tests/test_penalty.py
lightning/impl/tests/test_prank.py
lightning/impl/tests/test_primal_cd.py
lightning/impl/tests/test_primal_newton.py
lightning/impl/tests/test_prox.py
lightning/impl/tests/test_sag.py
lightning/impl/tests/test_sdca.py
lightning/impl/tests/test_sgd.py
lightning/impl/tests/test_svrg.py

Use pytest fixtures to parametrize existing tests. It allows to remove duplicated code (mainly, dataset generations), speed up tests, increase code readability. Also it improves test logs readability (see screenshot below), note additional square brackets in a test title.
Sorry, this PR looks quite huge for review, but you can hide whitespace changes and leave only meaningful ones (they are all similar across files).

Refactor tests to use pytest features

---

.github/workflows/main.yml

In a response to https://github.com/scikit-learn-contrib/lightning/pull/192#issuecomment-1019153279.

Automatically upload releases to PyPI

---

.github/workflows/main.yml

Refer to https://www.python.org/dev/peps/pep-0440/#version-scheme.

Exclude egg files during uploading PyPI release and allow `dev` and `post` release tags

---

.github/workflows/main.yml

Simply remove `.egg` files before creating PyPI release to avoid specific globbing patterns fail in some jobs.

Fix PyPI uploads
